name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
    Hello:
      description: 'Who to greet'
      required: false
      default: 'World'
    path_dockerfile:
      description: 'Path to the Dockerfile'
      required: true
    image_name:
      description: 'image_name'
      required: true
    tag_name:
      description: 'Tag name'
      required: true

runs:
  using: composite
  steps:
    - run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
          echo "TAG=$(date +%s)" >> $GITHUB_ENV
        else
          echo "TAG=${{ inputs.tag_name }}" >> $GITHUB_ENV
        fi
        echo "DOCKER_IMAGE_NAME=${{ inputs.image_name }}" >> $GITHUB_ENV 
        docker build . --file ${{ inputs.path_dockerfile }} --tag TAG