name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
    Hello:
      description: 'Who to greet'
      required: true
      default: 'World'
runs:
  using: composite
  steps:
    - run: |
        echo "Hello World"
      shell: bash