name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: list Docker images
      run: docker images
      with:
        tag_name: 'doc'
        image_name: 'docke'
        path_dockerfile: 'C:\Users\CTW03591\Desktop\academy\Dockerfile'
    - uses: joaojoaofernandes/academy/.github/actions/docker_build@main

