name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: list Docker images
      uses: joaojoaofernandes/academy/.github/actions/docker_build@main
      with:
        tag_name: 'latest'
        image_name: 'academy'
      

